#!/bin/bash

# Azure OpenAI Fine-Tuning Quick Reference Commands
# Source: https://learn.microsoft.com/en-us/azure/ai-foundry/openai/how-to/fine-tuning?tabs=azure-openai&pivots=rest-api

# Set environment variables first:
# export AZURE_OPENAI_ENDPOINT="https://<your-resource-name>.openai.azure.com"
# export AZURE_OPENAI_API_KEY="<your-api-key>"

echo "=== Azure OpenAI Fine-Tuning Quick Commands ==="

echo "1. Upload Training Data:"
echo "curl -X POST \$AZURE_OPENAI_ENDPOINT/openai/v1/files \\"
echo "  -H \"Content-Type: multipart/form-data\" \\"
echo "  -H \"api-key: \$AZURE_OPENAI_API_KEY\" \\"
echo "  -F \"purpose=fine-tune\" \\"
echo "  -F \"file=@training_set.jsonl;type=application/json\""
echo ""

echo "2. Upload Validation Data:"
echo "curl -X POST \$AZURE_OPENAI_ENDPOINT/openai/v1/files \\"
echo "  -H \"Content-Type: multipart/form-data\" \\"
echo "  -H \"api-key: \$AZURE_OPENAI_API_KEY\" \\"
echo "  -F \"purpose=fine-tune\" \\"
echo "  -F \"file=@validation_set.jsonl;type=application/json\""
echo ""

echo "3. Create Fine-Tuning Job:"
echo "curl -X POST \$AZURE_OPENAI_ENDPOINT/openai/v1/fine_tuning/jobs \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"api-key: \$AZURE_OPENAI_API_KEY\" \\"
echo "  -d '{"
echo "    \"model\": \"gpt-4.1-2025-04-14\","
echo "    \"training_file\": \"<TRAINING_FILE_ID>\","
echo "    \"validation_file\": \"<VALIDATION_FILE_ID>\","
echo "    \"seed\": 105"
echo "  }'"
echo ""

echo "4. Check Job Status:"
echo "curl -X GET \$AZURE_OPENAI_ENDPOINT/openai/v1/fine_tuning/jobs/<JOB_ID> \\"
echo "  -H \"api-key: \$AZURE_OPENAI_API_KEY\""
echo ""

echo "5. List Checkpoints:"
echo "curl -X GET \$AZURE_OPENAI_ENDPOINT/openai/v1/fine_tuning/jobs/<JOB_ID>/checkpoints \\"
echo "  -H \"api-key: \$AZURE_OPENAI_API_KEY\""
echo ""

echo "6. Copy Model (Preview):"
echo "curl --request POST \\"
echo "  --url 'https://<aoai-resource>.openai.azure.com/openai/v1/fine_tuning/jobs/<ftjob>/checkpoints/<checkpoint>/copy' \\"
echo "  --header 'Content-Type: application/json' \\"
echo "  --header 'api-key: <api-key>' \\"
echo "  --header 'aoai-copy-ft-checkpoints: preview' \\"
echo "  --data '{"
echo "    \"destinationResourceId\": \"<resourceId>\","
echo "    \"region\": \"<region>\""
echo "  }'"
echo ""

echo "7. Pause Job:"
echo "curl -X POST \$AZURE_OPENAI_ENDPOINT/openai/v1/fine_tuning/jobs/<JOB_ID>/pause \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"api-key: \$AZURE_OPENAI_API_KEY\""
echo ""

echo "8. Resume Job:"
echo "curl -X POST \$AZURE_OPENAI_ENDPOINT/openai/v1/fine_tuning/jobs/<JOB_ID>/resume \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"api-key: \$AZURE_OPENAI_API_KEY\""
echo ""

echo "9. Deploy Model (Management API):"
echo "curl -X POST \"https://management.azure.com/subscriptions/<SUB>/resourceGroups/<RG>/providers/Microsoft.CognitiveServices/accounts/<NAME>/deployments/<DEPLOYMENT>?api-version=2024-10-21\" \\"
echo "  -H \"Authorization: Bearer <TOKEN>\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"sku\": {\"name\": \"standard\", \"capacity\": 1},"
echo "    \"properties\": {"
echo "      \"model\": {"
echo "        \"format\": \"OpenAI\","
echo "        \"name\": \"<FINE_TUNED_MODEL>\","
echo "        \"version\": \"1\""
echo "      }"
echo "    }"
echo "  }'"
echo ""

echo "10. Download Results:"
echo "# First get job details to find result file ID"
echo "curl -X GET \$AZURE_OPENAI_ENDPOINT/openai/v1/fine_tuning/jobs/<JOB_ID> \\"
echo "  -H \"api-key: \$AZURE_OPENAI_API_KEY\""
echo ""
echo "# Then download the results CSV"
echo "curl -X GET \$AZURE_OPENAI_ENDPOINT/openai/v1/files/<RESULT_FILE_ID>/content \\"
echo "  -H \"api-key: \$AZURE_OPENAI_API_KEY\" > results.csv"
echo ""

echo "=== End of Quick Reference ==="